# Generated by Django 4.2.5 on 2023-09-23 11:19

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='book_have',
            field=models.ForeignKey(null=True, on_delete=builtins.callable, to='home.book'),
        ),
    ]
