# Generated by Django 4.2.5 on 2023-09-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_student_book_have_book_student_have'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_end',
        ),
    ]
