# Generated by Django 4.2.5 on 2023-09-23 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_book_date_start_remove_book_student_have_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='date_start',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
